# AUTO-GENERATED — do not edit by hand.
# Regenerated by scripts/gen_version.py from pyproject.toml's
# [project] version on each build. Edit pyproject.toml to
# change the version; this file follows.

__version__ = "0.2.0.dev2"
