"""Codegen: write daimon/_version.py from pyproject.toml's version.

Mirrors sdk/typescript/scripts/gen-version.mjs. Source of truth is
pyproject.toml's `[project] version` (the value setuptools encodes
into the wheel + sdist metadata that PyPI consumes). daimon/__init__.py
imports __version__ from daimon._version, so the runtime constant
can never drift from the package metadata — bumping pyproject.toml
and running this script automatically resyncs the constant.

Runs before `python -m build` in the publish pipeline. Locally,
re-run after bumping pyproject.toml. CI also re-runs it and fails
if the result diffs from the committed _version.py, so a missed
local re-run shows up as a PR failure rather than a stale release.

Uses regex parsing (not `tomllib`) so this script runs on Python
3.10 — pyproject's `requires-python = ">=3.10"` matters for the
CI build matrix.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
PYPROJECT = ROOT / "pyproject.toml"
OUT = ROOT / "daimon" / "_version.py"


def read_version_from_pyproject(path: Path) -> str:
    """Pull the `version = "..."` line from pyproject.toml.

    Deliberately uses regex — tomllib is stdlib on 3.11+ only, and
    the build environment may be 3.10 (CI matrix floor). The shape
    of the line is rigid enough that a literal pattern is safe; if
    pyproject ever moves to dynamic versioning (e.g. setuptools-scm),
    revisit.
    """
    content = path.read_text(encoding="utf-8")
    # Match the FIRST `version = "..."` at the start of a line. Other
    # version-like lines (`requires-python = ">=3.10"`,
    # `min-python-version = "3.10"`) won't match because they don't
    # start with the bare key `version`.
    match = re.search(r'^version\s*=\s*"([^"]+)"', content, re.MULTILINE)
    if match is None:
        raise SystemExit(
            f"gen_version: no `version = \"...\"` line found in {path}"
        )
    return match.group(1)


def render(version: str) -> str:
    return (
        "# AUTO-GENERATED — do not edit by hand.\n"
        "# Regenerated by scripts/gen_version.py from pyproject.toml's\n"
        '# [project] version on each build. Edit pyproject.toml to\n'
        "# change the version; this file follows.\n"
        "\n"
        f'__version__ = "{version}"\n'
    )


def main() -> int:
    version = read_version_from_pyproject(PYPROJECT)
    body = render(version)
    OUT.write_text(body, encoding="utf-8")
    print(f"gen_version: wrote {OUT} (__version__={version!r})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
