// Codegen: write src/version.ts from package.json#version.
//
// Source of truth is package.json (the file npm/registry consume).
// src/index.ts imports VERSION from ./version.js so the runtime constant
// can never drift from the package metadata — bumping package.json and
// running `npm run build` automatically regenerates the constant.
//
// Run by the `gen-version` npm script, which is chained ahead of `build`
// and `prepublishOnly`. If you ever bump the version by hand outside the
// build pipeline, run `npm run gen-version` to resync.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const PKG_PATH = join(ROOT, "package.json");
const OUT_PATH = join(ROOT, "src", "version.ts");

const pkg = JSON.parse(readFileSync(PKG_PATH, "utf8"));
const version = pkg.version;
if (typeof version !== "string" || version.length === 0) {
  console.error(`gen-version: package.json#version is missing or empty`);
  process.exit(1);
}

const body = `// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen-version.mjs from package.json#version on
// each \`npm run build\` (and on \`prepublishOnly\` before \`npm publish\`).
// Edit package.json to change the version; this file follows.

export const VERSION = ${JSON.stringify(version)};
`;

writeFileSync(OUT_PATH, body, "utf8");
console.log(`gen-version: wrote ${OUT_PATH} (VERSION="${version}")`);
