package main

import (
	"fmt"
	"os"
)

// cmdCompletion prints a static shell-completion script for the
// requested shell to stdout. Users install via:
//
//	# bash (macOS Homebrew layout):
//	daimon completion bash > $(brew --prefix)/etc/bash_completion.d/daimon
//
//	# bash (Linux distro layout):
//	daimon completion bash > /etc/bash_completion.d/daimon
//
//	# zsh (most layouts — must be on $fpath):
//	daimon completion zsh > "${fpath[1]}/_daimon"
//
//	# fish:
//	daimon completion fish > ~/.config/fish/completions/daimon.fish
//
// The completions are STATIC — they enumerate the subcommand /
// flag / enum-value surface without round-tripping to the daemon.
// Dynamic completion (e.g. completing memory IDs from the actual
// store, completing wallet chains from the chain registry) is
// out of scope for v0.2; static covers ~95% of the day-to-day
// "I forgot the exact spelling of `show-mnemonic`" case.
//
// Keep these scripts in lockstep with cmd/daimon/main.go's
// subcommand router + each subcommand's flagset definitions. If
// a new top-level verb or a new --flag lands and these scripts
// don't, the completion just silently misses it — annoying but
// not broken. A CONTRIBUTING.md line nudges new-verb PRs to
// update completion too.
func cmdCompletion(args []string) error {
	if len(args) != 1 {
		return fmt.Errorf("usage: daimon completion <bash|zsh|fish>")
	}
	switch args[0] {
	case "bash":
		fmt.Fprint(os.Stdout, completionBash)
	case "zsh":
		fmt.Fprint(os.Stdout, completionZsh)
	case "fish":
		fmt.Fprint(os.Stdout, completionFish)
	default:
		return fmt.Errorf("daimon completion: unknown shell %q (supported: bash, zsh, fish)", args[0])
	}
	return nil
}

// --- bash completion --------------------------------------------------------

const completionBash = `# bash completion for daimon — generated by 'daimon completion bash'.
# Source from your bashrc, or drop into /etc/bash_completion.d/.

_daimon_completion() {
    local cur prev words cword
    _init_completion -n = 2>/dev/null || {
        # _init_completion isn't available everywhere (e.g. minimal
        # containers); fall back to a manual setup.
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    }

    local top_verbs="init unlock identity memory provider chat doctor activity wallet payment rotate-password backup restore completion version help"
    local memory_verbs="write read list search delete export import"
    local provider_verbs="list invoke"
    local activity_verbs="query verify"
    local wallet_verbs="list create address derive sign show-mnemonic recover"
    local payment_verbs="pay"
    local memory_kinds="fact preference task observation"
    local shells="bash zsh fish"

    # Top-level subcommand
    if [[ $cword -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$top_verbs" -- "$cur") )
        return
    fi

    # Second-level: dispatch by the top-level verb
    local top="${words[1]}"
    case "$top" in
        memory)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$memory_verbs" -- "$cur") )
                return
            fi
            # --kind value completion (e.g. 'daimon memory write --kind <TAB>')
            if [[ "$prev" == "--kind" ]]; then
                COMPREPLY=( $(compgen -W "$memory_kinds" -- "$cur") )
                return
            fi
            ;;
        provider)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$provider_verbs" -- "$cur") )
                return
            fi
            ;;
        activity)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$activity_verbs" -- "$cur") )
                return
            fi
            ;;
        wallet)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$wallet_verbs" -- "$cur") )
                return
            fi
            ;;
        payment)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$payment_verbs" -- "$cur") )
                return
            fi
            ;;
        completion)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$shells" -- "$cur") )
                return
            fi
            ;;
        backup|restore|identity)
            # Path-completion is the natural fall-through for --to / <path>.
            ;;
    esac

    # Default: complete filenames (covers --to <path>, restore <path>, etc.)
    _filedir 2>/dev/null || COMPREPLY=( $(compgen -f -- "$cur") )
}

complete -F _daimon_completion daimon
`

// --- zsh completion ---------------------------------------------------------

const completionZsh = `#compdef daimon
# zsh completion for daimon — generated by 'daimon completion zsh'.
# Place on $fpath (e.g. ~/.zsh/completions/_daimon), then ` + "`compinit`" + `.

_daimon() {
    local -a top_verbs memory_verbs provider_verbs activity_verbs wallet_verbs payment_verbs memory_kinds shells
    top_verbs=(
        'init:Provision a fresh keystore in $DAIMON_HOME'
        'unlock:Load the keystore and unlock the daemon'
        'identity:Print the principal DID'
        'memory:Memory subcommands (write/read/list/search/...)'
        'provider:Provider subcommands (list/invoke)'
        'chat:Conversational REPL with multi-turn history'
        'doctor:Read-only environment health probe'
        'activity:Activity-log subcommands (query/verify)'
        'wallet:Wallet subcommands (list/create/address/derive/sign/show-mnemonic/recover)'
        'payment:Payment subcommands (pay)'
        'rotate-password:Change at-rest password for identity+wallet keystores'
        'backup:Snapshot the whole daimon into a single file'
        'restore:Inverse of backup; supports --dry-run for verification'
        'completion:Print a shell-completion script (bash/zsh/fish)'
        'version:Print the CLI version'
        'help:Show usage'
    )
    memory_verbs=(write read list search delete export import)
    provider_verbs=(list invoke)
    activity_verbs=(query verify)
    wallet_verbs=(list create address derive sign show-mnemonic recover)
    payment_verbs=(pay)
    memory_kinds=(fact preference task observation)
    shells=(bash zsh fish)

    if (( CURRENT == 2 )); then
        _describe 'daimon subcommand' top_verbs
        return
    fi

    local top=$words[2]
    case "$top" in
        memory)
            if (( CURRENT == 3 )); then
                _describe 'memory subcommand' memory_verbs
                return
            fi
            if [[ $words[CURRENT-1] == "--kind" ]]; then
                _describe 'memory kind' memory_kinds
                return
            fi
            ;;
        provider)
            (( CURRENT == 3 )) && { _describe 'provider subcommand' provider_verbs; return }
            ;;
        activity)
            (( CURRENT == 3 )) && { _describe 'activity subcommand' activity_verbs; return }
            ;;
        wallet)
            (( CURRENT == 3 )) && { _describe 'wallet subcommand' wallet_verbs; return }
            ;;
        payment)
            (( CURRENT == 3 )) && { _describe 'payment subcommand' payment_verbs; return }
            ;;
        completion)
            (( CURRENT == 3 )) && { _describe 'shell' shells; return }
            ;;
    esac

    _files
}

_daimon "$@"
`

// --- fish completion --------------------------------------------------------

const completionFish = `# fish completion for daimon — generated by 'daimon completion fish'.
# Drop into ~/.config/fish/completions/daimon.fish; fish auto-loads.

# Helper: predicate for "are we at the Nth token of a daimon command?"
function __daimon_using_command
    set -l cmd (commandline -opc)
    set -l want $argv
    if test (count $cmd) -le (count $want)
        return 1
    end
    for i in (seq (count $want))
        if test "$cmd[(math $i + 1)]" != "$want[$i]"
            return 1
        end
    end
    return 0
end

# Top-level subcommands
complete -c daimon -f -n "not __fish_seen_subcommand_from init unlock identity memory provider chat doctor activity wallet payment rotate-password backup restore completion version help" \
    -a "init unlock identity memory provider chat doctor activity wallet payment rotate-password backup restore completion version help"

# Second-level
complete -c daimon -f -n "__daimon_using_command memory" -a "write read list search delete export import"
complete -c daimon -f -n "__daimon_using_command provider" -a "list invoke"
complete -c daimon -f -n "__daimon_using_command activity" -a "query verify"
complete -c daimon -f -n "__daimon_using_command wallet" -a "list create address derive sign show-mnemonic recover"
complete -c daimon -f -n "__daimon_using_command payment" -a "pay"
complete -c daimon -f -n "__daimon_using_command completion" -a "bash zsh fish"

# --kind values for memory write / etc.
complete -c daimon -f -l kind -n "__daimon_using_command memory write" -a "fact preference task observation"
complete -c daimon -f -l kind -n "__daimon_using_command memory list" -a "fact preference task observation"
complete -c daimon -f -l kind -n "__daimon_using_command memory search" -a "fact preference task observation"
`
