// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen-version.mjs from package.json#version on
// each `npm run build` (and on `prepublishOnly` before `npm publish`).
// Edit package.json to change the version; this file follows.

export const VERSION = "0.1.0";
