"""Pytest fixtures: stub Unix-socket JSON-RPC daemon.

The stub listens on a temp socket, decodes one JSON request per
connection, and responds with a JSON-RPC response generated by a
test-supplied handler dict (``{method_name: callable_or_response}``).
The wire shape matches the Go server's dispatcher exactly, so the SDK's
client code is exercised against a byte-for-byte real protocol.
"""

from __future__ import annotations

import json
import os
import shutil
import socket
import tempfile
import threading
from collections.abc import Callable, Iterator
from pathlib import Path
from typing import Any

import pytest


# Valid memory kinds per SPEC §5.2. Keep in sync with
# internal/memory/memory.go:41 — the daemon rejects writes with any other
# kind via -32004 invalid memory kind, and the stub mirrors that so test
# fixtures can't silently drift from production validation.
VALID_MEMORY_KINDS = frozenset({"fact", "preference", "task", "observation"})


class StubDaemon:
    """A tiny Unix-socket JSON-RPC server for SDK tests.

    Each connection is one request, one response, then close — exactly
    matching cmd/daimon/rpc.go's per-call connection lifecycle. Handlers
    can be either:

    * a plain dict/list/scalar — sent back as the ``result`` field
    * a callable ``(params) -> Any`` — return value goes into ``result``;
      to return a JSON-RPC error, raise :class:`StubRPCError`.
    """

    def __init__(self, socket_path: Path):
        self.socket_path = socket_path
        self.calls: list[tuple[str, Any]] = []
        self._handlers: dict[str, Any] = {}
        self._stream_handlers: dict[str, tuple[Any, Any]] = {}
        self._sock: socket.socket | None = None
        self._thread: threading.Thread | None = None
        self._stop = threading.Event()

    def handle(self, method: str, response: Any) -> None:
        """Register a handler for one method. Overwrites any prior."""
        self._handlers[method] = response

    def stream(self, method: str, deltas: Any, terminal: Any) -> None:
        """Register a streaming handler.

        ``deltas`` is either a list of strings (sent verbatim as
        ``daimon.provider.stream.delta`` notifications, in order) or a
        callable ``(params) -> list[str]``.

        ``terminal`` is the final response — either a dict (sent as the
        terminal frame's ``result``), a :class:`StubRPCError` instance
        (sent as the terminal frame's ``error``), or a callable
        ``(params) -> dict | StubRPCError``.

        The stub does not require the client to half-close the write
        side — it dispatches based on the first newline-terminated JSON
        object on the wire, which matches both the streaming and the
        non-streaming wire framing.
        """
        self._stream_handlers[method] = (deltas, terminal)

    def start(self) -> None:
        if self.socket_path.exists():
            self.socket_path.unlink()
        self._sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        self._sock.bind(str(self.socket_path))
        self._sock.listen(8)
        self._sock.settimeout(0.2)
        self._thread = threading.Thread(target=self._accept_loop, daemon=True)
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()
        if self._sock is not None:
            try:
                self._sock.close()
            except OSError:
                pass
        if self._thread is not None:
            self._thread.join(timeout=2.0)
        try:
            if self.socket_path.exists():
                self.socket_path.unlink()
        except OSError:
            pass

    def _accept_loop(self) -> None:
        assert self._sock is not None
        while not self._stop.is_set():
            try:
                conn, _ = self._sock.accept()
            except socket.timeout:
                continue
            except OSError:
                return
            threading.Thread(
                target=self._serve_one, args=(conn,), daemon=True
            ).start()

    def _serve_one(self, conn: socket.socket) -> None:
        with conn:
            conn.settimeout(5.0)
            # Read until the first newline — the SDK always appends one,
            # for both streaming and non-streaming. This works regardless
            # of whether the client half-closes the write side.
            buf = bytearray()
            while b"\n" not in buf:
                try:
                    chunk = conn.recv(4096)
                except OSError:
                    return
                if not chunk:
                    break
                buf.extend(chunk)
            if not buf:
                return
            nl = buf.find(b"\n")
            line = bytes(buf[:nl] if nl >= 0 else buf)
            if not line.strip():
                return
            try:
                req = json.loads(line)
            except json.JSONDecodeError:
                resp = _err_response(None, -32700, "parse error")
                conn.sendall((json.dumps(resp) + "\n").encode())
                return

            method = req.get("method", "")
            params = req.get("params")
            req_id = req.get("id", 1)
            self.calls.append((method, params))

            if method == "daimon.memory.write" and isinstance(params, dict):
                kind = params.get("kind")
                if not isinstance(kind, str) or kind not in VALID_MEMORY_KINDS:
                    resp = _err_response(req_id, -32004, "invalid memory kind")
                    conn.sendall((json.dumps(resp) + "\n").encode())
                    return

            stream_pair = self._stream_handlers.get(method)
            if stream_pair is not None:
                self._serve_stream(conn, stream_pair, params, req_id)
                return

            handler = self._handlers.get(method)
            if handler is None:
                resp = _err_response(req_id, -32601, f"method not found: {method}")
            else:
                try:
                    if callable(handler):
                        result = handler(params)
                    else:
                        result = handler
                    resp = {"jsonrpc": "2.0", "result": result, "id": req_id}
                except StubRPCError as e:
                    resp = _err_response(req_id, e.code, e.message, e.data)

            conn.sendall((json.dumps(resp) + "\n").encode())

    def _serve_stream(
        self,
        conn: socket.socket,
        stream_pair: tuple[Any, Any],
        params: Any,
        req_id: Any,
    ) -> None:
        deltas_arg, terminal_arg = stream_pair
        deltas = deltas_arg(params) if callable(deltas_arg) else list(deltas_arg)
        terminal = terminal_arg(params) if callable(terminal_arg) else terminal_arg

        try:
            for d in deltas:
                notif = {
                    "jsonrpc": "2.0",
                    "method": "daimon.provider.stream.delta",
                    "params": {"content": d},
                }
                conn.sendall((json.dumps(notif) + "\n").encode())

            if isinstance(terminal, StubRPCError):
                resp = _err_response(req_id, terminal.code, terminal.message, terminal.data)
            else:
                resp = {"jsonrpc": "2.0", "result": terminal, "id": req_id}
            conn.sendall((json.dumps(resp) + "\n").encode())
        except (BrokenPipeError, ConnectionResetError, OSError):
            # Client may have closed the socket mid-stream (early exit, etc).
            # Real daemons swallow this; tests should too — surfacing it as
            # a thread exception was failing the suite on the early-exit case.
            return


class StubRPCError(Exception):
    """Raise from a handler callable to send a JSON-RPC error envelope."""

    def __init__(self, code: int, message: str, data: Any = None):
        self.code = code
        self.message = message
        self.data = data
        super().__init__(f"{code}: {message}")


def _err_response(req_id: Any, code: int, message: str, data: Any = None) -> dict:
    err: dict[str, Any] = {"code": code, "message": message}
    if data is not None:
        err["data"] = data
    return {"jsonrpc": "2.0", "error": err, "id": req_id}


@pytest.fixture()
def short_tmp() -> Iterator[Path]:
    """Per-test tempdir under ``/tmp`` (short enough for AF_UNIX).

    Pytest's default ``tmp_path`` lives under macOS's
    ``/var/folders/.../pytest-of-<user>/pytest-<n>/<test>/`` which already
    exceeds the 104-byte AF_UNIX ``sun_path`` cap before we even append a
    filename. Anything that needs to bind a Unix socket must root its
    paths somewhere shorter — ``/tmp/dt-<rand>/`` keeps us under cap.
    """
    base = Path(tempfile.mkdtemp(prefix="dt-", dir="/tmp"))
    try:
        yield base
    finally:
        shutil.rmtree(base, ignore_errors=True)


@pytest.fixture()
def stub_daemon(short_tmp: Path) -> Iterator[StubDaemon]:
    """Yield a started StubDaemon listening on a temp socket."""
    sock_path = short_tmp / "daimon.sock"
    daemon = StubDaemon(sock_path)
    daemon.start()
    try:
        yield daemon
    finally:
        daemon.stop()


@pytest.fixture()
def daimon_home(short_tmp: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Set ``$DAIMON_HOME`` to a short temp dir for the duration of a test."""
    home = short_tmp / "home"
    home.mkdir(mode=0o700, exist_ok=True)
    monkeypatch.setenv("DAIMON_HOME", str(home))
    return home
